//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trineslation_Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trineslation_Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the installation folder of the Trine Editor.
        /// </summary>
        public static string ExtractGameInput {
            get {
                return ResourceManager.GetString("ExtractGameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an folder for exported XLIFF files.
        /// </summary>
        public static string ExtractGameOutput {
            get {
                return ResourceManager.GetString("ExtractGameOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the installation folder of the Trine game.
        /// </summary>
        public static string ExtractLauncherInput {
            get {
                return ResourceManager.GetString("ExtractLauncherInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an folder for exported XLIFF files.
        /// </summary>
        public static string ExtractLauncherOutput {
            get {
                return ResourceManager.GetString("ExtractLauncherOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder with translated XLIFF files.
        /// </summary>
        public static string PackGameInput {
            get {
                return ResourceManager.GetString("PackGameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the installation folder of the Trine Editor.
        /// </summary>
        public static string PackGameOutput {
            get {
                return ResourceManager.GetString("PackGameOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder with translated XLIFF files.
        /// </summary>
        public static string PackLauncherInput {
            get {
                return ResourceManager.GetString("PackLauncherInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the installation folder of the Trine game.
        /// </summary>
        public static string PackLauncherOutput {
            get {
                return ResourceManager.GetString("PackLauncherOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a game from the list.
        /// </summary>
        public static string PickGameFromListPrompt {
            get {
                return ResourceManager.GetString("PickGameFromListPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select input folder.
        /// </summary>
        public static string SelectInputFolder {
            get {
                return ResourceManager.GetString("SelectInputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output folder.
        /// </summary>
        public static string SelectOutputFolder {
            get {
                return ResourceManager.GetString("SelectOutputFolder", resourceCulture);
            }
        }
    }
}
